name: Upload Hidden Files

on: [push, pull_request]

jobs:
  upload-hidden-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Upload Artifacts (Including Hidden Files)
        uses: actions/upload-artifact@v4
        with:
          name: hidden-files
          path: |
            .  # Upload everything in the root directory
            .hidden-file  # Ensure the specific hidden file is included
          include-hidden-files: true
